# Generated by Django 6.1 on 2026-09-01 10:13

import django.db.models.deletion
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('object_type', models.CharField(blank=True, max_length=30)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=records.models.document_upload_path)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('language', models.CharField(choices=[('auto', 'Auto-detect'), ('eng', 'English'), ('hin', 'Hindi'), ('ben', 'Bengali'), ('tam', 'Tamil'), ('tel', 'Telugu'), ('kan', 'Kannada'), ('guj', 'Gujarati'), ('mar', 'Marathi'), ('pan', 'Punjabi')], default='auto', max_length=8)),
                ('detected_language', models.CharField(blank=True, max_length=8)),
                ('state_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('district_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=16)),
                ('ocr_engine', models.CharField(blank=True, max_length=80)),
                ('ocr_language', models.CharField(blank=True, max_length=40)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('ocr_text', models.TextField(blank=True)),
                ('preprocess_info', models.JSONField(blank=True, default=dict)),
                ('processing_log', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('survey_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('khasra_number', models.CharField(blank=True, max_length=120)),
                ('khata_number', models.CharField(blank=True, max_length=120)),
                ('plot_area', models.FloatField(blank=True, null=True)),
                ('area_unit', models.CharField(blank=True, max_length=32)),
                ('village', models.CharField(blank=True, db_index=True, max_length=120)),
                ('tehsil', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('land_classification', models.CharField(blank=True, max_length=160)),
                ('ownership_type', models.CharField(blank=True, max_length=80)),
                ('mutation_number', models.CharField(blank=True, max_length=60)),
                ('mutation_date', models.CharField(blank=True, max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=60)),
                ('registration_date', models.CharField(blank=True, max_length=20)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('review_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='records.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnedCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=40)),
                ('raw_value', models.TextField()),
                ('corrected_value', models.TextField()),
                ('times_applied', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('field_name', 'raw_value', 'corrected_value')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('OPERATOR', 'Digitization Operator'), ('VERIFIER', 'Verification Officer'), ('VIEWER', 'Read-only Viewer')], default='VIEWER', max_length=16)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(db_index=True, max_length=40)),
                ('field_name', models.CharField(blank=True, max_length=40)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=10)),
                ('message', models.CharField(max_length=400)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='records.landrecord')),
            ],
            options={
                'ordering': ['severity', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='FieldExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=40)),
                ('value', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('ocr', 'OCR + rules'), ('learned', 'AI auto-correction'), ('manual', 'Manual verification')], default='ocr', max_length=12)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('corrected_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='records.landrecord')),
            ],
            options={
                'unique_together': {('record', 'field_name')},
            },
        ),
    ]
