# Generated by Django 6.1 on 2026-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldextraction',
            name='method',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='subdivision_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
