# Generated by Django 6.1 on 2026-09-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_fieldextraction_method_landrecord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldextraction',
            name='source',
            field=models.CharField(choices=[('ocr', 'OCR + rules'), ('learned', 'Verified-correction memory'), ('manual', 'Manual verification')], default='ocr', max_length=12),
        ),
    ]
